# Site settings
title: Valentin Heidelberger
default_author: Valentin Heidelberger
description: "Valentin Heidelberger's blog"  # used in site head

# register on feedburner and replace this url. Deleting the value will remove it from footer.
#feedburner_url: https://feedburner.google.com/fb/a/mailverify?uri=programmer-wannabe&amp;loc=en_US

# footer details. Deleting the value would remove it from footer.
github_username:  va1entin
twitter_username : valhei
linkedin_username : shikherverma42
copyright_name: Valentin Heidelberger
rss : true

# used for portfolio on home page
collections:
  - portfolio

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
port: 8888
permalink: /blog/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: blog/page:num

# gem dependencies
plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
